# https://alacritty.org/config-alacritty.html

[env]
TERM = "xterm-256color"

[font]
size = 18.0

[font.normal]
family = "MesloLGS Nerd Font Mono"

[font.offset]
x = 1
y = 2

[keyboard]
bindings = [
  # https://stackoverflow.com/a/78008190
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left",  mods = "Alt", chars = "\u001BB" },
]

[scrolling]
history = 100000
multiplier = 1

[window]
#decorations = "Buttonless"
decorations = "Full"
option_as_alt = "Both"
dynamic_padding = true
#opacity = 0.96
#blur = true
startup_mode = "Fullscreen"

[window.dimensions]
columns = 120
lines = 40

[window.padding]
x = 10
y = 10

