#!/bin/bash -e

# a wrapper for docker that launches it if it's not running
#  -- assumes macOS with Docker.app installed :p

command="$(basename "${0}")"

if [ "${0}" == "$(command -v "${command}")" ]; then
    path_to_remove="$(dirname "${0}")"
    PATH="${PATH[@]/$path_to_remove}"
    if [ -z "$(echo "${PATH}" | sed 's/://g' 2>/dev/null)" ]; then
        echo "could not find ${command}; not in path?" >&2
	exit 1
    fi

    if [ "${0}" == "$(command -v "${command}")" ]; then
      echo "could not remove myself from PATH; refusing to proceed" >&2
      exit 1
    fi
fi

function _launch_docker_if_not_running() {
    if docker version >/dev/null 2>&1; then return 0; fi
    if ! docker desktop start; then return 1; fi
}

function _wrapper() {
    if [ "$(sw_vers -productName 2>/dev/null)" == 'macOS' ]; then
        _launch_docker_if_not_running
    fi
    "${command}" "${@}"
}

_wrapper "${@}"

