#!/bin/zsh -e

# a wrapper for docker that launches it if it's not running
#  -- assumes macOS with Docker.app installed :p

function _launch_docker_if_not_running() {
    TIMEOUT=$(( $(date +%s) + 60))
    if docker version >/dev/null 2>&1; then return 0; fi
    echo "Launching Docker.app" >&2
    if ! open -a Docker; then return 1; fi
    while [ $(date +%s) -lt ${TIMEOUT} ]; do
        if docker version >/dev/null 2>&1; then return 0; fi
        sleep 1
    done
    echo "Timeout waiting for Docker.app" >&2
    return 1
}

function _docker_wrapper() {
    if [ "$(sw_vers --productName 2>/dev/null)" == 'macOS' ]; then
        _launch_docker_if_not_running
    fi
    docker "${@}"
}

docker_wrapper "${@}"

